### ISSUE TITLE
when using camera component, controller offset is not applied

### ISSUE THREAD

**Issue by caseyyee** [ryanbetts/aframe-daydream-controller-component#6]
Controller origin starts at camera position (rather than offset)

```html
<!-- does not work: -->
<a-entity camera></a-entity>

<!-- works -->
<a-camera></a-camera>
```

**Comment by machenmusik** [comment]
@caseyyee got a codepen for this?

**Comment by caseyyee** [comment]
Here's a shot of the screen using `<a-entity camera look-controls></a-entity>`
![image](https://cloud.githubusercontent.com/assets/1560884/23530245/be7b8b20-ff55-11e6-82f0-f62fee870882.png)

Codepen here:
http://codepen.io/caseyyee/pen/Mpypry
(looks like the dist needs to be bumped (shows VIVE controller), but the issue is the same.

**Comment by machenmusik** [comment]
the problem is that userHeight is zero in this case, and the code is trying to scale the eyesToElbow offset by user height (which is now zero).  I think the right answer is to have the degenerate arm model use a default value instead of zero (say, the traditional 1.6)

@caseyyee the scene looks kinda weird given that you put the camera in the floor ;-)

**Comment by machenmusik** [comment]
fixed here:  http://codepen.io/machenmusik/pen/RpaXbj

expect PR shortly.
